apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          terminationMessagePath: "/tmp/my-log"
          env:
           - name: ACCEPT_EULA
             value: "Y"
           - name: SA_PASSWORD
             valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: SA_PASSWORD
          ports:
             - containerPort: 1433
          volumeMounts:
           - name: mssql-data
             mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:

          claimName: sql-db-claim
