

apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
     name: mssql-pod
     app: mssql-app
spec:
   containers:
      - name: mssql
        image: docker pull mcr.microsoft.com/mssql/server
        ports:
          - containerPort: 1433
