apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
     app: mssql-app
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer